spring.application.name=multi-tenant-inventory

spring.datasource.url=jdbc:postgresql://localhost:5432/tenant-system-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# show queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true